### PR TITLE
Add Flush to force aggregate in-memory buffer

### LINKED ISSUE #862: Make it possible for opencensus to pass all remaining data to registered exporters when program exits.
Problem:

When exiting a program running opencensus monitoring, some of the data are not passed to exporter. This happens because as one can see in following code, reportUsage() is called only by timer, so when program exists, all data passed to opencensus after last timer firing event are simply lost.

```
func (w *worker) start() {
	for {
		select {
		case cmd := <-w.c:
			cmd.handleCommand(w)
		case <-w.timer.C:
			w.reportUsage(time.Now())
		case <-w.quit:
			w.timer.Stop()
			close(w.c)
			w.done <- true
			return
		}
	}
}
```

Solution proposal:
1. Make `func (w *worker) stop()` to be (indirectly) callable by client of package.
2. Make `func (w *worker) start()` to call `w.reportUsage()` before returning when `<-w.quit` is triggered.

### PR DESCRIPTION
**Pull request by rakyll**
Fixes #862.

### CODE REVIEW

**Comment by odeke-em** [comment]
@rakyll thanks for also working on this! I had mailed #922 sometime back. However, be ware that calling Flush after any future stops shouldn't block :)

**Comment by bogdandrutu** [comment]
@rakyll I think (RetrieveData)[https://github.com/census-instrumentation/opencensus-go/blob/master/stats/view/worker.go#L94] is your answer for this. See how I used it https://github.com/census-instrumentation/opencensus-service/blob/master/observability/observabilitytest/observabilitytest.go#L105

Do you think that is enough?

**Comment by wdhnl** [comment]
Can this be looked at again?

**Comment by rakyll** [comment]
Closing this due to inactivity, please open another PR if it needs to be addressed.

**Pull request closed without merging**
