### PR TITLE
Update ochttp stats according to spec.

### PR DESCRIPTION
**Pull request by johansja**
Related to this issue: https://github.com/census-instrumentation/opencensus-go/issues/742

### CODE REVIEW

**Comment by johansja** [comment]
It seems like the failure was caused by something else. And when I ran the test locally, it works fine.

**Comment by rghetia** [comment]
@johansja I think it would be best to make this change in opentelemetry given that it would create a breaking change.

**Comment by johansja** [comment]
Thanks for looking into this. Would you consider adding some tag key to the view a breaking change?

The main thing that I am trying to achieve right now is to add route-specific metrics such as latency.

**Comment by rghetia** [comment]
> Thanks for looking into this. Would you consider adding some tag key to the view a breaking change?
> 
> The main thing that I am trying to achieve right now is to add route-specific metrics such as latency.

It is not a breaking change but it adds another dimension which will increase number of time-series for everyone. That is not desirable. You could create your own view and have route tag in it.

**Comment by bogdandrutu** [comment]
@johansja you can define your own views that include the route and keep the default without for the moment. This is just an idea.

**Comment by johansja** [comment]
Hi all, thanks for the suggestion. I guess the custom view or forking might be the way to go temporarily while we wait for OpenTelemetry to be more mature. Hopefully, OpenTelemetry will have metrics per route by default.

**Pull request closed without merging**
