### PR TITLE
Add custom spanID for create span

### PR DESCRIPTION
**Pull request by llhhbc**
I have a custom span with use customer spanID.

### CODE REVIEW

**Comment by llhhbc** [comment]
@googlebot I signed it!

**Comment by llhhbc** [comment]
@googlebot I fixed it

**Comment by llhhbc** [comment]
@googlebot I fixed it

**Comment by dashpole** [comment]
Hey @llhhbc, unfortunately we aren't accepting new features at this time.  The OpenCensus community is currently collaborating on OpenTelemetry, and that project is accepting new features, although they are currently focused on releasing 1.0.

**Pull request closed without merging**
