### PR TITLE
Fix a couple of broken links on the exporters

### PR DESCRIPTION
**Pull request by montera82**
### Description
Fix a couple of broken links on the exporters

### CODE REVIEW

**Comment by montera82** [comment]
I signed it!

**Comment by montera82** [comment]
hi  @lychung83 @rakyll

**Comment by songy23** [comment]
ping @googlebot

**Comment by rakyll** [comment]
@montera82 Did you use a different email address than the committer email when signing the CLA? I cannot verify it.

**Comment by montera82** [comment]
@rakyll , schade,  i have now reflected my public email to match the one which i signed the cla with, could you crosscheck one more time. Danke

image

**Pull request merged**
