### PR TITLE
Typecast num into int64

### LINKED ISSUE #893: zpages: `constant 1000000000000 overflows int` build error for 32bit architectures
**Describe the bug**
I am using `go.opencensus.io/zpages` in my [project](https://github.com/sipian/prometheus/blob/opencensus-tracing/web/web.go#L449).

When I am building my project using `GOOS=${goos} GOARCH=${arch} go build .`
for the following architectures, 
`linux-386, darwin-386, windows-386, freebsd-386, openbsd-386, netbsd-386, linux-armv5, freebsd-armv6, netbsd-armv6`

I am getting the following error
`/go/src/github.com/prometheus/prometheus/vendor/go.opencensus.io/zpages/templates.go:66:9: constant 1000000000000 overflows int`

**Expected behavior**
My project should compile successfully for the above mentioned platforms.

### PR DESCRIPTION
**Pull request by sipian**
Fixes #893 

Signed-off-by: Harsh Agarwal <cs15btech11019@iith.ac.in>

### CODE REVIEW

**Comment by odeke-em** [comment]
Thank you very much for reporting that bug @sipian and welcome to OpenCensus!

LGTM but perhaps we could tighten that code a little more or perhaps even re-write that section like this
```diff
diff --git a/zpages/templates.go b/zpages/templates.go
index d60a12d..6826493 100644
--- a/zpages/templates.go
+++ b/zpages/templates.go
@@ -58,20 +58,23 @@ func parseTemplate(name string) *template.Template {
 }
 
 func countFormatter(num int) string {
-	if num == 0 {
+	if num <= 0 {
 		return " "
 	}
 	var floatVal float64
 	var suffix string
-	if num >= 1e12 {
-		floatVal = float64(num) / 1e9
-		suffix = " T "
-	} else if num >= 1e9 {
-		floatVal = float64(num) / 1e9
-		suffix = " G "
-	} else if num >= 1e6 {
-		floatVal = float64(num) / 1e6
+	num64 := int64(num)
+
+	switch {
+	case num64 <= 1e6:
+		floatVal = float64(num64) / 1e3
 		suffix = " M "
+	case num64 <= 1e9:
+		floatVal = float64(num64) / 1e6
+		suffix = " G "
+	default:
+		floatVal = float64(num64) / 1e9
+		suffix = " T "
 	}
 
 	if floatVal != 0 {
```

For now either patches will work, but with the issue that you reported, I am now worried about the design choices of this library, for making a couple of fields int, cast from float64, causing losses of precision as you've even noted here. On 32bit architectures, we won't even get to more than 2GB using int aka int32

**Comment by sipian** [comment]
I have amended by commit to the desired changes.
PTAL

**Comment by odeke-em** [comment]
@songy23 the CI appveyor check is failing for no reason related to this patch
screen shot 2018-09-04 at 9 14 46 am

Could you please retoggle it or disable it?

**Comment by songy23** [comment]
Looks like I don't have permission to restart the build :( 
@sipian could you make an [empty commit](https://coderwall.com/p/vkdekq/git-commit-allow-empty) to re-trigger the CI build? The CI failure should have nothing to do with this PR.

**Comment by songy23** [comment]
Looks like this has something to do with the appveyor hosts - sorry I don't have permissions to modify the setting of this repo either.
@ramonza  @rakyll Could either of you make `appveyor` build optional, since it's very flaky at this moment?

**Comment by rakyll** [comment]
Doing it.

**Comment by rakyll** [comment]
@sipian Can you push again?

**Pull request merged**
