### PR TITLE
Replace "x/net/context" import with "context"

### PR DESCRIPTION
**Pull request by rakyll**
We also need to pin to a gRPC version that includes
https://github.com/grpc/grpc-go/commit/04ea82009cdb9ecdefc6289f4c93ec919a10b3b6.

### CODE REVIEW

**Comment by rakyll** [comment]
@jadekler We need a new gRPC version to merge this PR.

**Comment by jadekler** [comment]
Woohoo!!

@rakyll Should be coming Dec 3rd, I think? cc @menghanl

**Comment by bogdandrutu** [comment]
@rakyll is this safe to merge now?

**Comment by bogdandrutu** [comment]
@rakyll have you had the chance to talk to gRPC devs about this?

**Comment by jadekler** [comment]
Speaking for myself, I believe this is safe. We have done likewise in several Go libraries and the last few gRPC versions have migrated to not using x/net/context.

**Comment by bogdandrutu** [comment]
@rakyll can we get this in the next couple of days?

**Comment by songy23** [comment]
Friendly ping. Should we rebase and merge this PR?

**Comment by rakyll** [comment]
Can someone else work on a PR from scratch instead? Closing this PR now.

**Pull request closed without merging**
