### PR TITLE
exporter/stats/stackdriver: name metric types consistently

### LINKED ISSUE #209: exporter/stats/stackdriver: name metrics consistently
OpenCensus Java names the metric descriptors in the form of:

```
OpenCensus/grpc.io/rountrip_latency/cumulative
```

We use lowercase "opencensus" as a prefix. Fix the inconsistency problem.

### PR DESCRIPTION
**Pull request by rakyll**
Fixes #209.

### CODE REVIEW

**Comment by rakyll** [comment]
Fixing it soon, sorry.

**Comment by rakyll** [comment]
PTAL

**Comment by rakyll** [comment]
I will follow up with a test.

**Comment by odeke-em** [comment]
Awesome, thanks.

**Pull request merged**
