### PR TITLE
fix buckets in example/quickstart

### PR DESCRIPTION
**Pull request by logicalhan**
Buckets for the distribution are not correctly aligned with what is present in the accompanying comment. This PR fixes that.

### CODE REVIEW

**Comment by rghetia** [comment]
@logicalhan thanks for the PR. Do you mind resubmitting the PR to dev branch?

**Comment by logicalhan** [comment]
Sure thing. Would you like to scrap this PR?

**Comment by rghetia** [comment]
> Sure thing. Would you like to scrap this PR?

yes, please.

**Comment by logicalhan** [comment]
PR recreated for dev: https://github.com/census-instrumentation/opencensus-go/pull/1132

**Pull request closed without merging**
