### PR TITLE
Fix syntax for view.Subscribe example.

### PR DESCRIPTION
**Pull request by wcn3**

### CODE REVIEW

**Comment by wcn3** [comment]
r:rakyll

**Comment by odeke-em** [comment]
Thank you for the catch @wcn3!

So to update the README, it's an undocumented process that involves the following:
1. Instead of editing the README itself, please edit internal/readme/README.md
2. Please run these instructions https://github.com/census-instrumentation/opencensus-go/tree/master/internal/readme

**Comment by wcn3** [comment]
Done. It looks like I've also picked up some other changes to the README.

**Comment by odeke-em** [comment]
Just one more request: so for the changes that got added to the README, could you please propagate them back to the internal like you did for the snippets, then regenerate them? Ideally only changes from internal/readme/README.md should appear in README.md.

**Comment by wcn3** [comment]
Done. PTAL.

**Pull request merged**
