### PR TITLE
Fix CI, and update testify

### PR DESCRIPTION
**Pull request by dashpole**
Address https://github.com/census-instrumentation/opencensus-go/pull/1283#issuecomment-1298899577

Also, update testify, and run `go fmt`.

Fixes https://github.com/census-instrumentation/opencensus-go/issues/1282

### CODE REVIEW

**Comment by punya** [comment]
The changes in this PR seem safe, but are we concerned that this might make it easy for us to break pre-1.18 users in future PRs?

**Comment by dashpole** [comment]
> The changes in this PR seem safe, but are we concerned that this might make it easy for us to break pre-1.18 users in future PRs?

We don't currently test multiple versions, so we might be breaking any version other than the one we are testing.  1.18 seemed reasonable, since it is 1 behind the latest go release.

**Review by punya — DISMISSED** [review]

**Comment by punya** [comment]
OpenCensus is meant to be in maintenance mode, so I would expect the minimum required versions of its dependencies to remain unchanged unless there's a high priority bugfix or security vulnerability. This should apply to the Go version as well.

I would support
* updating the documentation to handle recent versions of Go correct (`go install` vs `go get`)
* narrowly updating the testify dependency to fix the problem

I would want OpenCensus-Go to keep building and testing against an *old* version of Go, and relying on the backwards compatibility of the Go language and stdlib for newer versions.

Happy to discuss in person if I'm misunderstanding the purpose of this PR.

**Comment by dashpole** [comment]
@punya 
done

**Review by punya — APPROVED** [review]

**Pull request merged**
