### PR TITLE
Allow setting the http route from HTTP handlers

### PR DESCRIPTION
**Pull request by sagikazarmark**
This PR implements the proposed and discussed fix in #944 

I think it would be nice to rewrite the test to a table drive approach, the current testing code contains duplications. If you agree, I will update the tests as well.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Travis failure seems to be unrelated

**Comment by rghetia** [comment]
> Travis failure seems to be unrelated

#1016 fixed the build failure. Please rebase it.

**Comment by sagikazarmark** [comment]
DOne, thanks @rghetia

**Comment by sagikazarmark** [comment]
@rghetia done

**Comment by sagikazarmark** [comment]
@rghetia thanks for merging! Do you want me to rewrite the tests into a table-driven one in a subsequent PR? (See my initial comment)

**Comment by rghetia** [comment]
> @rghetia thanks for merging! Do you want me to rewrite the tests into a table-driven one in a subsequent PR? (See my initial comment)

that would be nice. Thx.

**Pull request merged**
